"""empty message

Revision ID: c585d01f258b
Revises: db84d8e46086
Create Date: 2024-01-06 22:52:42.382524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c585d01f258b'
down_revision = 'db84d8e46086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('presenter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'presenters', ['presenter_id'], ['presenter_id'])
    op.add_column('presenters', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'presenters', 'users', ['user_id'], ['user_id'])
    op.add_column('ticket_orders', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('ticket_orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ticket_orders', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'ticket_orders', 'events', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_orders', type_='foreignkey')
    op.drop_constraint(None, 'ticket_orders', type_='foreignkey')
    op.drop_column('ticket_orders', 'user_id')
    op.drop_column('ticket_orders', 'event_id')
    op.drop_constraint(None, 'presenters', type_='foreignkey')
    op.drop_column('presenters', 'user_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'presenter_id')
    # ### end Alembic commands ###
