"""empty message

Revision ID: 49fb678c320a
Revises: 6176fd63f203
Create Date: 2024-01-06 23:36:53.022457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fb678c320a'
down_revision = '6176fd63f203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'time')
    # ### end Alembic commands ###
