"""empty message

Revision ID: 8b8958195f81
Revises: 49fb678c320a
Create Date: 2024-01-06 23:40:09.098330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b8958195f81'
down_revision = '49fb678c320a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=True))
    op.drop_column('events', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###
